<div align="center"><h1>{$maintitle}</h1></div>
<strong>Welcome to {$package}!</strong><br />
<br />
<h2>kjsahdkjsahdkjh</h2>
This documentation was generated by <a href="{$phpdocwebsite}">phpDocumentor v{$phpdocversion}</a>
<br />

